-- migrate:up
INSERT INTO public.manga_series (title, genre, author, volumes, status, release_year, publisher, description) VALUES
    ('Starstream Saga', 'Supernatural', 'Yuki Morita', 9, 'Ongoing', 2015, 'Kadokawa', 'A whimsical manga about starstream saga.'),
    ('Neon Neko', 'Mystery', 'Nao Suzuki', 3, 'Ongoing', 2010, 'Square Enix', 'A whimsical manga about neon neko.'),
    ('Mystic Melody', 'Horror', 'Kuro Takeda', 5, 'Finished', 2015, 'Kadokawa', 'A whimsical manga about mystic melody.'),
    ('Phantom Quill', 'Mystery', 'Ami Hoshino', 14, 'Finished', 2018, 'Viz Media', 'A whimsical manga about phantom quill.'),
    ('Sakura Steel', 'Mystery', 'Ami Hoshino', 12, 'Finished', 2023, 'Shueisha', 'A whimsical manga about sakura steel.'),
    ('Celestial Circuit', 'Fantasy', 'Mika Arai', 9, 'Finished', 2010, 'Shogakukan', 'A whimsical manga about celestial circuit.'),
    ('Shadow Shrine', 'Sci-Fi', 'Rin Takahashi', 17, 'Ongoing', 2011, 'Square Enix', 'A whimsical manga about shadow shrine.'),
    ('Radiant Requiem', 'Comedy', 'Sora Inoue', 14, 'Finished', 2019, 'Kodansha', 'A whimsical manga about radiant requiem.'),
    ('Moonlit Mirage', 'Fantasy', 'Haru Kudo', 13, 'Finished', 2014, 'Yen Press', 'A whimsical manga about moonlit mirage.'),
    ('Crimson Canvas', 'Romance', 'Haru Kudo', 7, 'Ongoing', 2021, 'Shueisha', 'A whimsical manga about crimson canvas.'),
    ('Echo Ember', 'Mystery', 'Haru Kudo', 9, 'Finished', 2023, 'Kodansha', 'A whimsical manga about echo ember.'),
    ('Blade Ballet', 'Mystery', 'Yuki Morita', 17, 'Finished', 2010, 'Shogakukan', 'A whimsical manga about blade ballet.'),
    ('Mythic Mosaic', 'Drama', 'Nao Suzuki', 24, 'Finished', 2013, 'Square Enix', 'A whimsical manga about mythic mosaic.'),
    ('Cosmic Chronicle', 'Action', 'Ami Hoshino', 10, 'Finished', 2020, 'Viz Media', 'A whimsical manga about cosmic chronicle.'),
    ('Nightfall Nymph', 'Action', 'Ami Hoshino', 23, 'Ongoing', 2017, 'Yen Press', 'A whimsical manga about nightfall nymph.'),
    ('Rune Runner', 'Comedy', 'Emi Fujimoto', 4, 'Finished', 2024, 'Shogakukan', 'A whimsical manga about rune runner.'),
    ('Pixel Pilgrimage', 'Fantasy', 'Rin Takahashi', 14, 'Finished', 2020, 'Shogakukan', 'A whimsical manga about pixel pilgrimage.'),
    ('Samurai Sonata', 'Fantasy', 'Haru Kudo', 13, 'Ongoing', 2014, 'Kadokawa', 'A whimsical manga about samurai sonata.'),
    ('Quantum Queen', 'Supernatural', 'Sora Inoue', 7, 'Finished', 2014, 'Shogakukan', 'A whimsical manga about quantum queen.'),
    ('Lunar Lancer', 'Romance', 'Ami Hoshino', 7, 'Ongoing', 2022, 'Kadokawa', 'A whimsical manga about lunar lancer.'),
    ('Oracle Opera', 'Mystery', 'Emi Fujimoto', 15, 'Finished', 2011, 'Square Enix', 'A whimsical manga about oracle opera.'),
    ('Gilded Ghost', 'Romance', 'Yuki Morita', 21, 'Finished', 2013, 'Shogakukan', 'A whimsical manga about gilded ghost.'),
    ('Twilight Tempest', 'Supernatural', 'Kei Tanaka', 20, 'Ongoing', 2011, 'Square Enix', 'A whimsical manga about twilight tempest.'),
    ('Harbor Halo', 'Drama', 'Mika Arai', 10, 'Ongoing', 2011, 'Square Enix', 'A whimsical manga about harbor halo.'),
    ('Dream Dossier', 'Adventure', 'Mika Arai', 17, 'Ongoing', 2018, 'Shogakukan', 'A whimsical manga about dream dossier.'),
    ('Abyssal Aria', 'Supernatural', 'Ami Hoshino', 24, 'Finished', 2017, 'Kodansha', 'A whimsical manga about abyssal aria.'),
    ('Violet Vanguard', 'Mystery', 'Mika Arai', 17, 'Finished', 2010, 'Yen Press', 'A whimsical manga about violet vanguard.'),
    ('Horizon Halo', 'Fantasy', 'Emi Fujimoto', 3, 'Finished', 2013, 'Square Enix', 'A whimsical manga about horizon halo.'),
    ('Spectral Symphony', 'Mystery', 'Sora Inoue', 17, 'Ongoing', 2021, 'Shogakukan', 'A whimsical manga about spectral symphony.'),
    ('Frostfire Fable', 'Drama', 'Yuki Morita', 17, 'Ongoing', 2023, 'Viz Media', 'A whimsical manga about frostfire fable.'),
    ('Mirage Maiden', 'Sci-Fi', 'Kei Tanaka', 14, 'Ongoing', 2017, 'Kodansha', 'A whimsical manga about mirage maiden.'),
    ('Nebula Nomad', 'Drama', 'Ami Hoshino', 18, 'Ongoing', 2022, 'Kadokawa', 'A whimsical manga about nebula nomad.'),
    ('Titanium Tale', 'Supernatural', 'Kuro Takeda', 11, 'Finished', 2021, 'Shogakukan', 'A whimsical manga about titanium tale.'),
    ('Wisteria Warden', 'Adventure', 'Mika Arai', 6, 'Finished', 2017, 'Viz Media', 'A whimsical manga about wisteria warden.'),
    ('Solar Serenade', 'Fantasy', 'Mika Arai', 5, 'Finished', 2016, 'Yen Press', 'A whimsical manga about solar serenade.'),
    ('Iron Ivy', 'Comedy', 'Mika Arai', 24, 'Ongoing', 2012, 'Viz Media', 'A whimsical manga about iron ivy.'),
    ('Crystal Crest', 'Sci-Fi', 'Mika Arai', 22, 'Ongoing', 2018, 'Yen Press', 'A whimsical manga about crystal crest.'),
    ('Driftwood Dusk', 'Supernatural', 'Kuro Takeda', 4, 'Ongoing', 2016, 'Kadokawa', 'A whimsical manga about driftwood dusk.'),
    ('Opal Oracle', 'Horror', 'Yuki Morita', 14, 'Ongoing', 2024, 'Kadokawa', 'A whimsical manga about opal oracle.'),
    ('Crescent Courier', 'Comedy', 'Emi Fujimoto', 11, 'Finished', 2015, 'Yen Press', 'A whimsical manga about crescent courier.'),
    ('Thunder Thistle', 'Romance', 'Kei Tanaka', 23, 'Ongoing', 2020, 'Yen Press', 'A whimsical manga about thunder thistle.'),
    ('Velocity Veil', 'Action', 'Ami Hoshino', 7, 'Ongoing', 2016, 'Kadokawa', 'A whimsical manga about velocity veil.'),
    ('Zephyr Zenith', 'Fantasy', 'Kei Tanaka', 3, 'Finished', 2016, 'Viz Media', 'A whimsical manga about zephyr zenith.'),
    ('Echo Eclipse', 'Romance', 'Mika Arai', 11, 'Finished', 2013, 'Yen Press', 'A whimsical manga about echo eclipse.'),
    ('Phoenix Prism', 'Action', 'Ami Hoshino', 7, 'Finished', 2019, 'Shueisha', 'A whimsical manga about phoenix prism.'),
    ('Magnet Maiden', 'Action', 'Mika Arai', 13, 'Finished', 2015, 'Viz Media', 'A whimsical manga about magnet maiden.'),
    ('Siren Scroll', 'Adventure', 'Haru Kudo', 7, 'Ongoing', 2020, 'Kadokawa', 'A whimsical manga about siren scroll.'),
    ('Aurora Anthem', 'Sci-Fi', 'Kuro Takeda', 7, 'Finished', 2013, 'Shogakukan', 'A whimsical manga about aurora anthem.'),
    ('Harlequin Horizon', 'Romance', 'Emi Fujimoto', 14, 'Finished', 2016, 'Kadokawa', 'A whimsical manga about harlequin horizon.'),
    ('Phantom Phoenix', 'Horror', 'Haru Kudo', 10, 'Finished', 2024, 'Yen Press', 'A whimsical manga about phantom phoenix.'),
    ('Vortex Valkyrie', 'Drama', 'Yuki Morita', 20, 'Finished', 2023, 'Yen Press', 'A whimsical manga about vortex valkyrie.'),
    ('Obsidian Ode', 'Adventure', 'Kei Tanaka', 17, 'Finished', 2011, 'Shogakukan', 'A whimsical manga about obsidian ode.'),
    ('Lilac Labyrinth', 'Romance', 'Sora Inoue', 5, 'Ongoing', 2023, 'Square Enix', 'A whimsical manga about lilac labyrinth.'),
    ('Jade Jester', 'Sci-Fi', 'Nao Suzuki', 12, 'Ongoing', 2020, 'Shogakukan', 'A whimsical manga about jade jester.'),
    ('Marionette Moon', 'Sci-Fi', 'Kuro Takeda', 3, 'Ongoing', 2023, 'Square Enix', 'A whimsical manga about marionette moon.'),
    ('Rogue Rhapsody', 'Fantasy', 'Rin Takahashi', 18, 'Finished', 2014, 'Viz Media', 'A whimsical manga about rogue rhapsody.'),
    ('Warden Waltz', 'Sci-Fi', 'Kuro Takeda', 12, 'Finished', 2021, 'Square Enix', 'A whimsical manga about warden waltz.'),
    ('Dragon Dust', 'Drama', 'Kei Tanaka', 17, 'Finished', 2011, 'Kadokawa', 'A whimsical manga about dragon dust.'),
    ('Silhouette Symphony', 'Mystery', 'Kei Tanaka', 19, 'Ongoing', 2021, 'Shogakukan', 'A whimsical manga about silhouette symphony.'),
    ('Fable Forge', 'Supernatural', 'Emi Fujimoto', 8, 'Finished', 2022, 'Viz Media', 'A whimsical manga about fable forge.'),
    ('Sable Sky', 'Mystery', 'Nao Suzuki', 17, 'Ongoing', 2010, 'Shogakukan', 'A whimsical manga about sable sky.'),
    ('Torrent Tides', 'Supernatural', 'Sora Inoue', 3, 'Finished', 2019, 'Shogakukan', 'A whimsical manga about torrent tides.'),
    ('Petrichor Path', 'Adventure', 'Ami Hoshino', 18, 'Finished', 2016, 'Kodansha', 'A whimsical manga about petrichor path.'),
    ('Ember Elysium', 'Fantasy', 'Mika Arai', 18, 'Ongoing', 2020, 'Kodansha', 'A whimsical manga about ember elysium.'),
    ('Nimbus Night', 'Action', 'Mika Arai', 4, 'Ongoing', 2015, 'Yen Press', 'A whimsical manga about nimbus night.'),
    ('Gale Garden', 'Adventure', 'Kuro Takeda', 12, 'Ongoing', 2013, 'Shogakukan', 'A whimsical manga about gale garden.'),
    ('Celestial Cipher', 'Supernatural', 'Haru Kudo', 8, 'Finished', 2010, 'Viz Media', 'A whimsical manga about celestial cipher.'),
    ('Onyx Odyssey', 'Action', 'Nao Suzuki', 21, 'Ongoing', 2019, 'Kodansha', 'A whimsical manga about onyx odyssey.'),
    ('Sable Sonata', 'Horror', 'Sora Inoue', 11, 'Finished', 2024, 'Yen Press', 'A whimsical manga about sable sonata.'),
    ('Raven Requiem', 'Fantasy', 'Nao Suzuki', 9, 'Ongoing', 2011, 'Square Enix', 'A whimsical manga about raven requiem.'),
    ('Ivory Idol', 'Sci-Fi', 'Kei Tanaka', 23, 'Finished', 2020, 'Shueisha', 'A whimsical manga about ivory idol.'),
    ('Cobalt Chronicles', 'Fantasy', 'Sora Inoue', 3, 'Ongoing', 2011, 'Kodansha', 'A whimsical manga about cobalt chronicles.'),
    ('Auric Arc', 'Comedy', 'Haru Kudo', 6, 'Finished', 2014, 'Kadokawa', 'A whimsical manga about auric arc.'),
    ('Verdant Vale', 'Supernatural', 'Haru Kudo', 23, 'Finished', 2020, 'Kadokawa', 'A whimsical manga about verdant vale.'),
    ('Hallowed Harbor', 'Adventure', 'Ami Hoshino', 19, 'Ongoing', 2024, 'Kodansha', 'A whimsical manga about hallowed harbor.'),
    ('Mythos Mirage', 'Mystery', 'Sora Inoue', 3, 'Finished', 2018, 'Yen Press', 'A whimsical manga about mythos mirage.'),
    ('Solaris Song', 'Supernatural', 'Kuro Takeda', 17, 'Finished', 2015, 'Kadokawa', 'A whimsical manga about solaris song.'),
    ('Quantum Quill', 'Drama', 'Sora Inoue', 23, 'Ongoing', 2023, 'Yen Press', 'A whimsical manga about quantum quill.'),
    ('Ethereal Echoes', 'Supernatural', 'Sora Inoue', 9, 'Ongoing', 2024, 'Kodansha', 'A whimsical manga about ethereal echoes.'),
    ('Wraith Waltz', 'Adventure', 'Nao Suzuki', 11, 'Finished', 2021, 'Kadokawa', 'A whimsical manga about wraith waltz.'),
    ('Zenith Zephyr', 'Romance', 'Kuro Takeda', 7, 'Finished', 2017, 'Shogakukan', 'A whimsical manga about zenith zephyr.'),
    ('Tempest Tale', 'Fantasy', 'Kei Tanaka', 10, 'Finished', 2022, 'Square Enix', 'A whimsical manga about tempest tale.'),
    ('Arcane Atlas', 'Action', 'Emi Fujimoto', 5, 'Ongoing', 2024, 'Shueisha', 'A whimsical manga about arcane atlas.'),
    ('Basilisk Ballad', 'Mystery', 'Rin Takahashi', 10, 'Ongoing', 2014, 'Shueisha', 'A whimsical manga about basilisk ballad.'),
    ('Chromatic Cascade', 'Romance', 'Nao Suzuki', 3, 'Ongoing', 2014, 'Kadokawa', 'A whimsical manga about chromatic cascade.'),
    ('Nocturne Nexus', 'Drama', 'Mika Arai', 21, 'Finished', 2012, 'Kodansha', 'A whimsical manga about nocturne nexus.'),
    ('Mirage Mirage', 'Sci-Fi', 'Sora Inoue', 16, 'Ongoing', 2012, 'Shueisha', 'A whimsical manga about mirage mirage.'),
    ('Palindrome Page', 'Mystery', 'Haru Kudo', 6, 'Finished', 2024, 'Shogakukan', 'A whimsical manga about palindrome page.'),
    ('Cerulean Cipher', 'Adventure', 'Rin Takahashi', 25, 'Finished', 2019, 'Shogakukan', 'A whimsical manga about cerulean cipher.'),
    ('Ghoul Garden', 'Supernatural', 'Ami Hoshino', 6, 'Finished', 2016, 'Shueisha', 'A whimsical manga about ghoul garden.'),
    ('Orbit Oracle', 'Comedy', 'Emi Fujimoto', 15, 'Finished', 2022, 'Shogakukan', 'A whimsical manga about orbit oracle.'),
    ('Sapphire Silence', 'Romance', 'Kuro Takeda', 21, 'Finished', 2021, 'Shueisha', 'A whimsical manga about sapphire silence.'),
    ('Vivid Vortex', 'Adventure', 'Haru Kudo', 21, 'Ongoing', 2018, 'Shueisha', 'A whimsical manga about vivid vortex.'),
    ('Whispering Willow', 'Horror', 'Sora Inoue', 16, 'Finished', 2018, 'Viz Media', 'A whimsical manga about whispering willow.'),
    ('Amber Anthem', 'Supernatural', 'Sora Inoue', 24, 'Finished', 2013, 'Shueisha', 'A whimsical manga about amber anthem.'),
    ('Nebula Nymph', 'Action', 'Kuro Takeda', 17, 'Finished', 2013, 'Square Enix', 'A whimsical manga about nebula nymph.'),
    ('Gilded Glyph', 'Mystery', 'Emi Fujimoto', 11, 'Ongoing', 2013, 'Shueisha', 'A whimsical manga about gilded glyph.'),
    ('Pulsar Pages', 'Supernatural', 'Ami Hoshino', 10, 'Finished', 2015, 'Viz Media', 'A whimsical manga about pulsar pages.'),
    ('Radiant Rift', 'Horror', 'Nao Suzuki', 7, 'Ongoing', 2022, 'Shogakukan', 'A whimsical manga about radiant rift.'),
    ('Cryptic Chorus', 'Sci-Fi', 'Haru Kudo', 16, 'Finished', 2018, 'Kadokawa', 'A whimsical manga about cryptic chorus.');

-- migrate:down
DELETE FROM public.manga_series WHERE title IN (
    'Starstream Saga',
    'Neon Neko',
    'Mystic Melody',
    'Phantom Quill',
    'Sakura Steel',
    'Celestial Circuit',
    'Shadow Shrine',
    'Radiant Requiem',
    'Moonlit Mirage',
    'Crimson Canvas',
    'Echo Ember',
    'Blade Ballet',
    'Mythic Mosaic',
    'Cosmic Chronicle',
    'Nightfall Nymph',
    'Rune Runner',
    'Pixel Pilgrimage',
    'Samurai Sonata',
    'Quantum Queen',
    'Lunar Lancer',
    'Oracle Opera',
    'Gilded Ghost',
    'Twilight Tempest',
    'Harbor Halo',
    'Dream Dossier',
    'Abyssal Aria',
    'Violet Vanguard',
    'Horizon Halo',
    'Spectral Symphony',
    'Frostfire Fable',
    'Mirage Maiden',
    'Nebula Nomad',
    'Titanium Tale',
    'Wisteria Warden',
    'Solar Serenade',
    'Iron Ivy',
    'Crystal Crest',
    'Driftwood Dusk',
    'Opal Oracle',
    'Crescent Courier',
    'Thunder Thistle',
    'Velocity Veil',
    'Zephyr Zenith',
    'Echo Eclipse',
    'Phoenix Prism',
    'Magnet Maiden',
    'Siren Scroll',
    'Aurora Anthem',
    'Harlequin Horizon',
    'Phantom Phoenix',
    'Vortex Valkyrie',
    'Obsidian Ode',
    'Lilac Labyrinth',
    'Jade Jester',
    'Marionette Moon',
    'Rogue Rhapsody',
    'Warden Waltz',
    'Dragon Dust',
    'Silhouette Symphony',
    'Fable Forge',
    'Sable Sky',
    'Torrent Tides',
    'Petrichor Path',
    'Ember Elysium',
    'Nimbus Night',
    'Gale Garden',
    'Celestial Cipher',
    'Onyx Odyssey',
    'Sable Sonata',
    'Raven Requiem',
    'Ivory Idol',
    'Cobalt Chronicles',
    'Auric Arc',
    'Verdant Vale',
    'Hallowed Harbor',
    'Mythos Mirage',
    'Solaris Song',
    'Quantum Quill',
    'Ethereal Echoes',
    'Wraith Waltz',
    'Zenith Zephyr',
    'Tempest Tale',
    'Arcane Atlas',
    'Basilisk Ballad',
    'Chromatic Cascade',
    'Nocturne Nexus',
    'Mirage Mirage',
    'Palindrome Page',
    'Cerulean Cipher',
    'Ghoul Garden',
    'Orbit Oracle',
    'Sapphire Silence',
    'Vivid Vortex',
    'Whispering Willow',
    'Amber Anthem',
    'Nebula Nymph',
    'Gilded Glyph',
    'Pulsar Pages',
    'Radiant Rift',
    'Cryptic Chorus'

);
